---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Zenitugo/microservice-app-CD
    targetRevision: HEAD
    path: ./manifest/monitoring
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true